#!/usr/bin/env python3
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from ap_common import read_json


def load_optional(path):
    if not path:
        return None
    p = Path(path)
    return read_json(p) if p.exists() else None


def finding_table(findings):
    if not findings:
        return "No findings raised by the deterministic scripts. This does not mean the aircraft is safe to fly."
    lines = ["| Severity | Confidence | Possible cause | Evidence | Recommended checks |", "|---|---|---|---|---|"]
    for f in findings:
        ev = "<br>".join(str(x) for x in f.get("evidence", [])[:6])
        checks = "<br>".join(str(x) for x in f.get("recommended_checks", [])[:6])
        lines.append(f"| {f.get('severity','')} | {f.get('confidence','')} | {f.get('possible_cause') or f.get('finding','')} | {ev} | {checks} |")
    return "\n".join(lines)


def render(index=None, metrics=None, tuning=None, diagnosis=None, fft=None):
    lines = ["# ArduPilot log analysis report\n"]
    if diagnosis:
        lines.append("## Executive summary")
        lines.append(f"- User-reported symptom: {diagnosis.get('symptom_text')}")
        lines.append(f"- Diagnosis class: `{diagnosis.get('symptom_class')}`")
        lines.append(f"- Vehicle: {diagnosis.get('log',{}).get('vehicle') or (index or {}).get('vehicle') or 'unknown'}")
        lines.append(f"- Firmware: {diagnosis.get('log',{}).get('firmware') or (index or {}).get('firmware') or 'unknown'}")
        findings = diagnosis.get("primary_findings", [])
        if findings:
            top = findings[0]
            lines.append(f"- Most likely issue: **{top.get('possible_cause')}** ({top.get('confidence')} confidence)")
        else:
            lines.append("- Most likely issue: no single cause confirmed by available log data")
        lines.append(f"- Safety note: {diagnosis.get('safety_note')}\n")
        lines.append("## Ranked diagnosis")
        lines.append(finding_table(findings))
        lines.append("\n## Checked but not supported")
        checked = diagnosis.get("checked_but_not_supported", [])
        if checked:
            for c in checked[:50]:
                lines.append(f"- {c.get('check')}: {c.get('result')}")
        else:
            lines.append("- No unsupported checks were recorded.")
        lines.append("\n## Missing data")
        if diagnosis.get("missing_data"):
            for m in diagnosis["missing_data"]:
                lines.append(f"- `{m}`")
        else:
            lines.append("- No required messages missing for the chosen symptom map.")
        lines.append("\n## What cannot be concluded")
        if diagnosis.get("what_cannot_be_concluded"):
            for w in diagnosis["what_cannot_be_concluded"]:
                lines.append(f"- {w}")
        else:
            lines.append("- No additional limitations were generated by the deterministic diagnosis script. Still verify against the actual aircraft and full log context.")
        lines.append("\n## Generated diagnostic plots")
        for p in diagnosis.get("plots", []):
            lines.append(f"- `{p}`")

    else:
        lines.append("## Executive summary")
        if index:
            lines.append(f"- File: {index.get('file_name')}")
            lines.append(f"- Vehicle: {index.get('vehicle') or 'unknown'}")
            lines.append(f"- Firmware: {index.get('firmware') or 'unknown'}")
            lines.append(f"- Duration: {index.get('duration_s')} s")
        if metrics:
            lines.append(f"- Overall confidence: {metrics.get('confidence',{}).get('overall','unknown')}")
            if metrics.get("analysis_window"):
                lines.append(f"- Analysis window: `{metrics.get('analysis_window')}`")
            for r in metrics.get("confidence", {}).get("reasons", []):
                lines.append(f"- Confidence note: {r}")
        lines.append("")
        if tuning and tuning.get("findings"):
            lines.append("## Safety-critical and likely tuning findings")
            lines.append(finding_table(tuning.get("findings", [])))
        elif metrics and metrics.get("health", {}).get("errors", {}).get("count", 0):
            lines.append("## ERR messages")
            for e in metrics["health"]["errors"].get("rows", [])[:20]:
                lines.append(f"- `{e}`")
        else:
            lines.append("## Safety-critical findings")
            lines.append("No deterministic safety-critical finding was raised. This does not mean the vehicle is safe to fly.")
        lines.append("\n## Health metrics")
        if metrics:
            for key, value in metrics.get("health", {}).items():
                lines.append(f"### {key}\n```json\n{json.dumps(value, indent=2)[:6000]}\n```")
        lines.append("\n## Tuning metrics")
        if metrics:
            for key, value in metrics.get("tuning", {}).items():
                lines.append(f"### {key}\n```json\n{json.dumps(value, indent=2)[:6000]}\n```")
        if metrics and metrics.get("system_id", {}).get("present"):
            lines.append("\n## AutoTune / System ID")
            lines.append("```json")
            lines.append(json.dumps(metrics.get("system_id"), indent=2)[:6000])
            lines.append("```")
        if fft:
            lines.append("\n## FFT / noise spectrum")
            lines.append(f"- Available: {fft.get('available')}")
            if fft.get("reason"):
                lines.append(f"- Reason: {fft.get('reason')}")
            for p in fft.get("plots", []):
                lines.append(f"- Plot: `{p}`")
            if fft.get("peaks"):
                lines.append("### Dominant peaks")
                lines.append("| Field | Frequency Hz | Amplitude |")
                lines.append("|---|---:|---:|")
                for pk in fft["peaks"][:15]:
                    lines.append(f"| {pk.get('field')} | {pk.get('frequency_hz'):.2f} | {pk.get('amplitude'):.2f} |")
        if metrics and metrics.get("generic_messages"):
            lines.append("\n## Additional message summaries")
            for key, value in list(metrics.get("generic_messages", {}).items())[:20]:
                compact = {"rows": value.get("rows"), "numeric": dict(list((value.get("numeric") or {}).items())[:10])}
                lines.append(f"### {key}\n```json\n{json.dumps(compact, indent=2)[:3000]}\n```")
        lines.append("\n## What cannot be concluded")
        cannot = []
        present = set((metrics or {}).get("messages_present", []) or (index or {}).get("message_names", []))
        if "ESC" not in present and "ESCX" not in present and "EDT2" not in present:
            cannot.append("ESC-level confirmation of motor RPM/current/temperature/error/status is not possible because ESC/ESCX/EDT2 telemetry is missing.")
        elif "ESCX" in present and "ESC" not in present and "EDT2" not in present:
            cannot.append("ESCX duty/power/flags are available, but ESC RPM/current/temperature/error and EDT2 status confirmation are not available because ESC and EDT2 telemetry are missing.")
        if "RCOU" not in present:
            cannot.append("Actuator saturation cannot be confirmed because RCOU is missing.")
        elif metrics and metrics.get("health", {}).get("motor_outputs", {}).get("mapping_available") is False:
            cannot.append("Output mapping could not be confirmed from parameters; RCOU channel interpretation is generic.")
        if "VIBE" not in present:
            cannot.append("Processed vibration cannot be assessed because VIBE is missing.")
        if "RATE" not in present:
            cannot.append("Rate tracking cannot be assessed because RATE is missing.")
        if not cannot:
            cannot.append("A log report still cannot verify mechanical condition, wiring, prop orientation, CG, or flight readiness without physical inspection.")
        for c in cannot:
            lines.append(f"- {c}")
    return "\n".join(lines)+"\n"


def main() -> int:
    p = argparse.ArgumentParser(description="Assemble a markdown report from generated analysis JSON files.")
    p.add_argument("--index", default=None)
    p.add_argument("--metrics", default=None)
    p.add_argument("--tuning", default=None)
    p.add_argument("--diagnosis", default=None)
    p.add_argument("--fft", default=None)
    p.add_argument("--out", default="report.md")
    args = p.parse_args()
    index = load_optional(args.index)
    metrics = load_optional(args.metrics)
    tuning = load_optional(args.tuning)
    diagnosis = load_optional(args.diagnosis)
    fft = load_optional(args.fft)
    report = render(index=index, metrics=metrics, tuning=tuning, diagnosis=diagnosis, fft=fft)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(report, encoding="utf-8")
    print(f"Report written to {args.out}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
